// Takes the Material Symbols Rounded icons the app uses out of @material-symbols/svg-400 (Apache 2.0) and writes
// their paths to src/ui/symbols.ts, so only these few go into the build and nothing is loaded from the internet.
// Usage: node scripts/icons.mjs — run it after adding a name below.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '..');
const source = join(root, 'node_modules', '@material-symbols', 'svg-400', 'rounded');

/** Material Symbols names, «-fill» for the filled form. */
const NAMES = [
  // The interface.
  'search', 'menu', 'settings', 'arrow_back', 'arrow_forward', 'add', 'check', 'close', 'chevron_left', 'chevron_right',
  'keyboard_arrow_down', 'warning', 'open_in_new', 'download', 'keyboard', 'drag_indicator', 'resize', 'view_carousel',
  'unfold_less', 'keep', 'star', 'star-fill', 'description', 'calculate', 'sticky_note_2', 'account_circle', 'palette',
  // The AI.
  'wand_stars', 'mic', 'history',
  'tune', 'menu_book', 'info',
  // Organisations.
  'local_police', 'traffic', 'security', 'verified_user', 'military_tech', 'policy', 'gavel', 'balance',
  'account_balance', 'local_hospital', 'newspaper', 'cases', 'how_to_vote', 'skull', 'person',
];

const symbols = {};
for (const name of NAMES) {
  const svg = readFileSync(join(source, `${name}.svg`), 'utf8');
  if (!svg.includes('viewBox="0 -960 960 960"')) throw new Error(`${name}: unexpected viewBox`);
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) throw new Error(`${name}: ${paths.length} paths`);
  symbols[name] = paths[0];
}

const out = [
  '// Generated by scripts/icons.mjs from Material Symbols Rounded (Apache 2.0, https://fonts.google.com/icons). Do not edit.',
  '// Every path is drawn in the viewBox «0 -960 960 960».',
  '',
  'export const SYMBOLS = {',
  ...Object.entries(symbols).map(([name, d]) => `  ${JSON.stringify(name)}: ${JSON.stringify(d)},`),
  '} as const;',
  '',
  'export type SymbolName = keyof typeof SYMBOLS;',
  '',
].join('\n');
writeFileSync(join(root, 'src', 'ui', 'symbols.ts'), out);
console.log(`${NAMES.length} icons → src/ui/symbols.ts (${out.length} bytes)`);
