// Bundled server packs, generated by `npm run import` from data/<server>/sources.
import type { ServerPack } from '../core';
import tverskoi from './tverskoi.json';

export const TVERSKOI_PACK = tverskoi as unknown as ServerPack;
