// Bundled server packs, generated by `npm run import` from data/<server>/sources.
import type { ServerPack } from '../core';
import arbatskiy from './arbatskiy.json';
import tverskoi from './tverskoi.json';

export const TVERSKOI_PACK = tverskoi as unknown as ServerPack;
export const ARBATSKIY_PACK = arbatskiy as unknown as ServerPack;

/** Every server the app has laws for, by id; the first one is what a new profile starts on. */
export const PACKS: Record<string, ServerPack> = {
  tverskoi: TVERSKOI_PACK,
  arbatskiy: ARBATSKIY_PACK,
};

/** The pack of a server, or the first one for a profile that names a server the app no longer has. */
export const packFor = (server: string): ServerPack => PACKS[server] ?? TVERSKOI_PACK;
